services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://<username>:<password>@db:5432/<dbname>
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kawabanga17
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
